#ifndef _COMMUNICATION_H_
#define _COMMUNICATION_H_


#define DEBUG 1

#define PACK_SIZE 1024*5
#define W_PACK_SIZE 1024*5
#define MAX_NAME_LEN 1024

#define STATUS_OK 0
#define ERROR_IO 22

#define ANTOAN_NOP 0

#define CUTOMA_FUSE_STATFS 402
#define MATOCU_FUSE_STATFS 403
#define CUTOMA_FUSE_LOOKUP 406
#define MATOCU_FUSE_LOOKUP 407
#define CUTOMA_FUSE_GETATTR 408
#define MATOCU_FUSE_GETATTR 409
#define CUTOMA_FUSE_GETDIR 428
#define MATOCU_FUSE_GETDIR 429

// --- drw --- ser
#define CUTOMA_FUSE_REGISTER 600
#define MATOCU_FUSE_REGISTER 601

#define DRWTOSER_CREAT_FILE 602
#define SERTODRW_CREAT_FILE 602

#define DRWTOMA_JUDGE_NAME 604
#define MATODRW_JUDGE_NAME 605

#define DRWTOSER_WRITE_CHUNK 606
#define SERTODRW_WRITE_CHUNK 607

#define DRWTOSER_WRITE_CHUNK_END 608
#define SERTODRW_WRITE_CHUNK_END 609

#define DRWTOSER_FS_GETDIR 610
#define SERTODRW_FS_GETDIR 611

#define DRWTOSER_FUSE_READ_CHUNK 612
#define SERTODRW_FUSE_READ_CHUNK 613

// ---drw --- dat
#define CLITODAT_READ_INFO 800
#define DATTOCLI_READ_INFO 801

#define DRWTODAT_WRITE_INFO 802
#define DATTODRW_WRITE_INFO 803

// ---ser --- dat
#define SERTODAT_DISK_INFO 900
#define DATTOSER_DISK_INFO 901

#define SERTODAT_CREAT_CHUNK 902
#define DATTOSER_CREAT_CHUNK 903


#endif
